Fix function hoisting behaviour (non-strict mode)
facebook/hermes pull request #1547
Opened 2024-10-21 11:13 UTC by trossimel-sc

## Summary

Addresses #1455 

Hermes currently has divergent function hoisting behavior compared to QuickJS, V8, and JSC in non-strict mode. The following code prints `FAIL` instead of `SUCCESS`

```
{
    function promotedFunction(endRecursion) {
        if(endRecursion) {
            promotedFunction(true);
            return;
        }
        print ('SUCCESS');
    }

    callback = promotedFunction;
}

{
    function promotedFunction(endRecursion) {
        if(endRecursion) {
            promotedFunction(true);
            return;
        }
        print ('FAIL');
    }
}

callback(false);
```

This happens as scoped function promoted to global scope are treated as global functions, like for `var`. 
To fix this behaviour:

- Two declarations are created for a promoted identifier instead of one: a global and a scoped declaration, stored in `sideIdentifierDeclarationDecl_` and `promotedFunctionDecls_`
- If the identifier is promoted, we call `emitStore` on both pointers associated to the declarations

## Test Plan

- Added a unit test with the failing code

2024-10-23 13:13 UTC, trossimel-sc commented
Seems like the failing errors are due to auto generated checks

2024-10-24 23:11 UTC, avp commented
@trossimel-sc The `update-lit` build target will update the tests that are autogenerated, then `check-hermes` to run them. [`LIT_FILTER`](https://llvm.org/docs/CommandGuide/lit.html#cmdoption-lit-filter) will let you narrow down what exactly gets updated or run as well. Thanks for submitting this fix!

2024-11-01 22:03 UTC, tmikov commented
Hi, we really need the CLA before we can review it internally. Thanks!

2025-01-22 15:51 UTC, trossimel-sc commented
The CLA is signed and we can proceed with the review process 😄 .
We can start with this PR and `for await of` PR.
I also noticed the build is failing on `static_h`. Is this happening to me only?

2025-01-22 18:16 UTC, avp requested changes
Thanks!

Overall this seems like a reasonable solution to me, just one question/clarification on maintaining the binding table.

2025-01-22 18:16 UTC, avp commented on lib/Sema/SemanticResolver.cpp
> +    bindingTable_.put(ident->_name, Binding{decl, ident});
This needs a comment explaining what the special case is doing.

e.g. Why is it using `put` to override instead of `try_emplace` as below?

2025-01-22 18:16 UTC, avp commented on lib/IRGen/ESTreeIRGen.h
> +    auto declPromoted = getIDDeclPromoted(id);
```suggestion
    auto *declPromoted = getIDDeclPromoted(id);
```

2025-01-23 18:29 UTC, avp commented
> I also noticed the build is failing on static_h.

That should be fixed with ae186905e9b2d6c30e7015d3b418fba7aea51d11

2025-01-27 16:56 UTC, trossimel-sc commented
Thank you @avp !
Addressed :)

2025-01-30 00:26 UTC, avp commented
@trossimel-sc The internal failure is due to a bad interaction with lazy compilation.  Test case:
```
(function() {
  { function* x() {} }
})();

(function() {
  function* y() { yield 1; }
})();
```

Run that with
```
bin/hermes ~/test.js --lazy
```

and there'll be an assertion failure:
```
Assertion failed: (llvh::isa<CreateScopeInst>(RSI) && "variable must be initialized in its own function"), function emitStore, file ESTreeIRGen.cpp, line 1208.
fish: Job 1, 'bin/hermes ~/test.js --lazy' terminated by signal SIGABRT (Abort)
```

Some documentation about how lazy compilation works: https://github.com/facebook/hermes/blob/static_h/doc/LazyEvalCompilation.md

I haven't gone through and debugged but there's potentially some extra work that has to be done in the lazy compilation path due to the new information you've added to SemContext.

2025-02-02 18:07 UTC, trossimel-sc commented
Thank you, I am trying to understand the problem and find a way to fix it.
Seems like the address of identifier `x` and `y` are the same at some point, and even when a promoted decl is not set for `y` in `validateAndDeclareIdentifier`, the function `resolveIdentifierPromoted` does not return nullptr for `y`. Quite weird

2025-02-05 02:30 UTC, avp commented on lib/Sema/SemanticResolver.cpp
> +    semCtx_.clearPromotedDecls();
I think this is the right fix, good catch.

Let's also put a comment so we don't forget why: the `promotedDecls` is used immediately, and keyed off the `IdentifierNode`, which is freed between invocations of lazy compilation. We need to remove references in `SemContext` when freeing the AST, which happens at the end of each invocation of lazy compilation.

2025-02-11 17:41 UTC, avp commented
@trossimel-sc We have one more issue with lazy compilation.

Test case:
```
function foo() {
  var result;
  {
    let x = 0;
    result = ret;
    function ret() {
      return x;
    }
  }
  return result;
}

print(typeof foo());
```

This should print `function` but it prints `undefined` in lazy mode.

2025-02-23 23:48 UTC, trossimel-sc commented on lib/BCGen/HBC/HBC.cpp
> +  semCtx->clearPromotedDecls();
I noticed that I was clearing the promoted declarations after the AST generation and before the IR generation. Now I am doing it after the IR generation. Let's see if it passes the tests. Also, is there a more appropriate place to put this line of code?

2025-03-18 18:38 UTC, avp commented
d1cd9925c1b9deebfe7ca1c18dc5ed046b050c20

2025-03-18 18:38 UTC, closed without merging