arm64 simulators & catalyst support (#475)
facebook/hermes pull request #543
Opened 2021-06-30 07:35 UTC by Huxpro

Summary:
Edits build scripts to allow merging architectures into .xcframework instead of using lipo for building fat framework.
Adds compatibility with arm64 iOS Simulators on Apple M1 Macs and allows using Hermes with RN apps built for Mac Catalyst.

Fixes https://github.com/facebook/hermes/issues/460 and https://github.com/facebook/hermes/issues/468

Pull Request resolved: https://github.com/facebook/hermes/pull/475

Differential Revision: D29465045

Pulled By: Huxpro

2021-06-30 07:42 UTC, Huxpro commented
This is a rebased version of the original PR that we can use to tell whether or not the CI breakages were false negatives due to outdating issue.

2021-07-01 06:44 UTC, grabbou requested changes

2021-07-01 06:44 UTC, grabbou commented on utils/build-ios-framework.sh
> +    build_apple_framework "iphonesimulator" "x86_64;arm64" "$ios_deployment_target"
BTW, I do think we should brig `i386` back. We still support iOS 10.

Ref: https://github.com/facebook/hermes/pull/363#issuecomment-696626229

2021-07-01 06:53 UTC, grabbou commented
There are two more things that I would do, before merging this PR, both relatively easy:

1/ Add a new target to our unit tests, that would be Mac Catalyst, and make CI run and test it (similar to what we do for iOS and Mac already)

2/ For the time being, we cannot do the same for Apple Silicon, since it's not supported. Is there someone with Apple M1 to do the proper testing?

2021-07-05 12:03 UTC, grabbou commented
Let's merge this one with a failing CI and @titozzz will send a follow up PR renaming the destination folder from `iphoneos` to `universal`.

Context: the build fails when a folder contains both `.framework` and `.xcframework`, which happens right now as we put `.xcframework` into `iphoneos` folder that already has a `.framework` with iPhone slices only. 

https://github.com/CocoaPods/CocoaPods/issues/10759

2021-07-08 17:15 UTC, TheSavior commented
I believe we should be closing this one in favor of https://github.com/facebook/hermes/pull/546

2021-07-08 17:15 UTC, closed without merging